
package biblioteca;

import static biblioteca.Libro.contadorLibros;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Pantalla extends javax.swing.JFrame {

    
    ArrayList<Libro> catalogo = new ArrayList();
    int isbnLibroModificar; //Esta variable la usaré más tarde para almacenar el isbn solicitado al modificar libro
    
    
    public Pantalla() {
        initComponents();

        this.setTitle("BIBLIOTECA");
        this.setSize(860, 590);
        this.setLocationRelativeTo(null); //con esto la pantalla saldrá centrada     
        
       loadComboBox(); //necesitaremos este método más adelante para el combobox con Enum
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdialog1Añadir = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        btnAñadir2 = new javax.swing.JButton();
        btnLimpiarAñadir = new javax.swing.JButton();
        btnVolverAñadir = new javax.swing.JButton();
        labelERROR = new javax.swing.JLabel();
        jdialog2Ver = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        labelContador = new javax.swing.JLabel();
        btnVolverCatalogo = new javax.swing.JButton();
        jdialog3Modificar = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        labelResumen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtModificarTitulo = new javax.swing.JTextField();
        txtModificarPrecio = new javax.swing.JTextField();
        txtModificarPaginas = new javax.swing.JTextField();
        comboModificarCategoria = new javax.swing.JComboBox<>();
        btnModificar2 = new javax.swing.JButton();
        btnModificarLimpiar = new javax.swing.JButton();
        btnModificarVolver = new javax.swing.JButton();
        jdialog4SalaLectura = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lector1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lector2 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jdialog1Añadir.setMinimumSize(new java.awt.Dimension(843, 563));
        jdialog1Añadir.setSize(new java.awt.Dimension(843, 563));
        jdialog1Añadir.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Introduzca datos del libro y pulse AÑADIR");
        jdialog1Añadir.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 530, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ISBN");
        jdialog1Añadir.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("TITULO");
        jdialog1Añadir.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PRECIO");
        jdialog1Añadir.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nº PAGINAS");
        jdialog1Añadir.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
        jdialog1Añadir.getContentPane().add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 110, -1));
        jdialog1Añadir.getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 280, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CATEGORIA");
        jdialog1Añadir.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 120, -1));
        jdialog1Añadir.getContentPane().add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, -1));
        jdialog1Añadir.getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 150, -1));
        jdialog1Añadir.getContentPane().add(txtPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 120, -1));

        btnAñadir2.setBackground(new java.awt.Color(51, 255, 51));
        btnAñadir2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAñadir2.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir2.setText("AÑADIR");
        btnAñadir2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAñadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir2ActionPerformed(evt);
            }
        });
        jdialog1Añadir.getContentPane().add(btnAñadir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 180, 140));

        btnLimpiarAñadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLimpiarAñadir.setForeground(new java.awt.Color(51, 255, 51));
        btnLimpiarAñadir.setText("LIMPIAR");
        btnLimpiarAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAñadirActionPerformed(evt);
            }
        });
        jdialog1Añadir.getContentPane().add(btnLimpiarAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 180, 50));

        btnVolverAñadir.setBackground(new java.awt.Color(51, 255, 51));
        btnVolverAñadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolverAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAñadir.setText("VOLVER");
        btnVolverAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolverAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverAñadirActionPerformed(evt);
            }
        });
        jdialog1Añadir.getContentPane().add(btnVolverAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 180, 40));

        labelERROR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelERROR.setForeground(new java.awt.Color(255, 51, 0));
        jdialog1Añadir.getContentPane().add(labelERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 530, 50));

        jdialog2Ver.setMinimumSize(new java.awt.Dimension(975, 638));
        jdialog2Ver.setSize(new java.awt.Dimension(975, 638));
        jdialog2Ver.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CATALOGO BIBLIOTECA");
        jdialog2Ver.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 710, 50));

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Título", "Categoría", "Precio", "Nº páginas"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        jdialog2Ver.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 770, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nº de libros en el catálogo:");
        jdialog2Ver.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 536, 200, 30));

        labelContador.setBackground(new java.awt.Color(255, 255, 255));
        labelContador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelContador.setOpaque(true);
        jdialog2Ver.getContentPane().add(labelContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 40, 30));

        btnVolverCatalogo.setBackground(new java.awt.Color(204, 204, 0));
        btnVolverCatalogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVolverCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverCatalogo.setText("VOLVER");
        btnVolverCatalogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolverCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCatalogoActionPerformed(evt);
            }
        });
        jdialog2Ver.getContentPane().add(btnVolverCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 140, 40));

        jdialog3Modificar.setMinimumSize(new java.awt.Dimension(1003, 616));
        jdialog3Modificar.setSize(new java.awt.Dimension(1003, 616));
        jdialog3Modificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MODIFICAR LIBRO");
        jdialog3Modificar.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 840, 80));

        labelResumen.setBackground(new java.awt.Color(255, 255, 255));
        labelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos libro seleccionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        labelResumen.setOpaque(true);
        jdialog3Modificar.getContentPane().add(labelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 240, 130));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jdialog3Modificar.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 890, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Introducir nuevos datos:");
        jdialog3Modificar.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 210, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Título: ");
        jdialog3Modificar.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Precio: ");
        jdialog3Modificar.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Categoría: ");
        jdialog3Modificar.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Nº páginas: ");
        jdialog3Modificar.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));
        jdialog3Modificar.getContentPane().add(txtModificarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 260, -1));
        jdialog3Modificar.getContentPane().add(txtModificarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 170, -1));
        jdialog3Modificar.getContentPane().add(txtModificarPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 170, -1));

        comboModificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModificarCategoriaActionPerformed(evt);
            }
        });
        jdialog3Modificar.getContentPane().add(comboModificarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 260, -1));

        btnModificar2.setBackground(new java.awt.Color(255, 204, 51));
        btnModificar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificar2.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar2.setText("MODIFICAR");
        btnModificar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });
        jdialog3Modificar.getContentPane().add(btnModificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 280, 40));

        btnModificarLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarLimpiar.setForeground(new java.awt.Color(255, 204, 0));
        btnModificarLimpiar.setText("LIMPIAR");
        btnModificarLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLimpiarActionPerformed(evt);
            }
        });
        jdialog3Modificar.getContentPane().add(btnModificarLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 160, 40));

        btnModificarVolver.setBackground(new java.awt.Color(255, 204, 0));
        btnModificarVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificarVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarVolver.setText("VOLVER");
        btnModificarVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVolverActionPerformed(evt);
            }
        });
        jdialog3Modificar.getContentPane().add(btnModificarVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 160, 40));

        jdialog4SalaLectura.setMinimumSize(new java.awt.Dimension(854, 456));
        jdialog4SalaLectura.setSize(new java.awt.Dimension(854, 456));
        jdialog4SalaLectura.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("¡A LEER!");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jdialog4SalaLectura.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("¡A LEER!");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jdialog4SalaLectura.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 100, 40));

        jScrollPane2.setViewportView(lector1);

        jdialog4SalaLectura.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, -1));

        jScrollPane3.setViewportView(lector2);

        jdialog4SalaLectura.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 290, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("LECTOR 1 - LUIS");
        jdialog4SalaLectura.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("LECTORA 2 - LUISA ");
        jdialog4SalaLectura.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 140, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jdialog4SalaLectura.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 460));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIBLIOTECA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 550, 60));

        btnModificar.setBackground(new java.awt.Color(255, 204, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR LIBRO");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR LIBRO");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, 40));

        btnBuscar.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR LIBRO");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 40));

        btnAñadir.setBackground(new java.awt.Color(0, 255, 0));
        btnAñadir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("AÑADIR LIBRO");
        btnAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 40));

        btnOrdenar.setBackground(new java.awt.Color(255, 255, 102));
        btnOrdenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrdenar.setText("ORDENAR LIBROS");
        btnOrdenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 180, 40));

        btnVer.setBackground(new java.awt.Color(255, 255, 102));
        btnVer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVer.setText("VER LIBROS");
        btnVer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 180, 40));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 102, 0));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 180, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("SALA DE LECTURA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        jdialog1Añadir.setVisible(true);
        jdialog1Añadir.setLocationRelativeTo(null); //con esto la pantalla saldrá centrada  
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        //vaciar tabla
        DefaultTableModel vaciar_tabla = (DefaultTableModel) tablaCatalogo.getModel();
        vaciar_tabla.setNumRows(0); //elimina todas las filas de la tabla
        tablaCatalogo.setModel(vaciar_tabla); //establece el modelo vaciado en la tabla
        
        //añadir datos a la tabla     
        DefaultTableModel modelo = (DefaultTableModel)tablaCatalogo.getModel(); /* capturamos el modelo actual de la tabla y 
                                                                                    lo asignamos como por defecto */
        for(int i=0;i<catalogo.size();i++){ 
            Object[] fila = new Object[5]; //aquí creo un array para almacenar los datos de cada fila
            
           fila[0] = catalogo.get(i).getIsbn();
           fila[1] = catalogo.get(i).titulo;
           fila[2] = catalogo.get(i).getCategoria();
           fila[3] = catalogo.get(i).precio;
           fila[4] = catalogo.get(i).nPaginas;
           modelo.addRow(fila); //esto añade la fila ya completada al modelo
            
           tablaCatalogo.setModel(modelo); //establezco el modelo actualizado en la tabla
        }

        jdialog2Ver.setVisible(true); //la hacemos visible al final para que aparezca ya actualizada
        jdialog2Ver.setLocationRelativeTo(null); //con esto la pantalla saldrá centrada
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnAñadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir2ActionPerformed
        //capturamos la información del libro desde los campos
        int isbn;
        String titulo = txtTitulo.getText();
        int precio;
        int nPaginas;
        
        //aseguramos con un try-catch que el isbn sea un entero
        try {
            isbn = Integer.parseInt(txtISBN.getText());
            precio = Integer.parseInt(txtPrecio.getText());
            nPaginas = Integer.parseInt(txtPaginas.getText());
            
        } catch (NumberFormatException e) {
            
        //mostramos mensaje de error al usuario
            labelERROR.setText("ERROR: EL ISBN, el precio y el nº de páginas DEBEN SER UN NÚMERO ENTERO");
            return; //salimos del método 
        }

        
        
        Categoria categoria = (Categoria) comboCategoria.getSelectedItem(); //casting para convertir el item en un objeto de tipo Categoría.
        
        //verificamos si el campo isbn está lleno. Es el campo más importante, pues lo usamos para identificar
        if (isbn == 0) {
            
        //mostramos mensaje de error en la etiqueta invisible
        labelERROR.setText("ERROR: POR FAVOR, INTRODUZCA UN ISBN");
        
        } else {
            
        //verificamos si el isbn ya está en uso
        if (isbnYaExiste(isbn)) {
            
        //la etiqueta que estaba oculta muestra un mensaje de error
            labelERROR.setText("ERROR: EL ISBN INGRESADO YA ESTÁ EN USO");
            
        } else {
        
        //introducimos la información en el arraylist creando un objeto completo
        Libro libro = new Libro(isbn,titulo,categoria,precio,nPaginas);
        catalogo.add(libro);
        
        //actualizamos el contador de libros que hay en la tabla
        labelContador.setText("" + contadorLibros + "");
        
        //limpiamos los campos después de agregar el libro
        txtISBN.setText("");
        txtTitulo.setText("");
        txtPrecio.setText("");
        txtPaginas.setText("");
        comboCategoria.setSelectedIndex(-1);
        
        //limpiamos mensaje de error
        labelERROR.setText("");
        } 
      }
    }//GEN-LAST:event_btnAñadir2ActionPerformed

    private void btnVolverCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCatalogoActionPerformed
        jdialog2Ver.setVisible(false);
    }//GEN-LAST:event_btnVolverCatalogoActionPerformed

    private void btnVolverAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAñadirActionPerformed
        jdialog1Añadir.setVisible(false);
    }//GEN-LAST:event_btnVolverAñadirActionPerformed

    private void btnLimpiarAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAñadirActionPerformed
        txtISBN.setText("");
        txtTitulo.setText("");
        txtPrecio.setText("");
        txtPaginas.setText("");
        comboCategoria.setSelectedIndex(-1);
        labelERROR.setText("");
    }//GEN-LAST:event_btnLimpiarAñadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //capturamos el isbn introducido por el usuario
    String isbnEliminar = JOptionPane.showInputDialog(null, "Introduzca el ISBN del libro",
                                                    "Eliminar librol", JOptionPane.QUESTION_MESSAGE);
    
    //verificamos si se ha introducido un isbn
    if(isbnEliminar != null && !isbnEliminar.isEmpty()){
        int isbnEnArray = Integer.parseInt(isbnEliminar); /*convertimos a entero lo introducido por el usuario. 
                                    En teoría ya hemos establecido la condición de que el isbn sea entero, pero no está de más 
                                    crear la costumbre de hacer esto
                                                                    */
        
        //buscamos el libro por isbn en el inventario con un for each
        for (int i=0; i<catalogo.size(); i++) {
            if (catalogo.get(i).getIsbn() == isbnEnArray){
                //eliminamos el libro cuando hay una coincidencia
                catalogo.remove(i);
                
                //disminuimos en 1 el contador de libros llamando al método estático que lo hace
                Libro.reducirContadorLibros();
                labelContador.setText("" + contadorLibros + "");
                
                //mostramos mensaje de confirmación de que el libro ha sido eliminado    
                JOptionPane.showMessageDialog(null, "Libro eliminado correctamente",
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                //salimos tras eliminar el libro
                return;
            }
        }
        
        //mostrar un mensaje si el librol no se encuentra en el catálogo
        JOptionPane.showMessageDialog(null, "No se encontró ningún libro con el isbn introducido: " + isbnEliminar,
                "Libro no encontrado", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
            //capturamos el isbn introducido por el usuario
        String isbnBusqueda = JOptionPane.showInputDialog(null, 
                "Introduzca el isbn del libro", "Buscar libro", 
                JOptionPane.QUESTION_MESSAGE);
        
        //verificamos si se ha introducido un isbn
        if(isbnBusqueda != null && !isbnBusqueda.isEmpty()){
            int isbnEnArray = Integer.parseInt(isbnBusqueda);
            
            //buscamos el libro por isbn en el inventario con un for each
            for (Libro l: catalogo){
                if(l.getIsbn() == isbnEnArray){
                    //Mostrar la información del libro encontrado
                    JOptionPane.showMessageDialog(null,
                            "ISBN: " + l.getIsbn() + "\n" +
                            "Título: " + l.titulo + "\n" +
                            "Categoria: " + l.getCategoria().toString() + "\n" +
                            "Precio: " + l.precio+ "\n" +
                            "Nº páginas: " + l.nPaginas,
                            
                            "Libro encontrado", JOptionPane.INFORMATION_MESSAGE);
                    
                    //salimos tras encontrar el libro
                    return;
                }
            }
            
            //mostrar un mensaje si el libro no se encuentra en el catálogo
            JOptionPane.showMessageDialog(null, 
                    "No se encontró ningún libro con el isbn introducido: " + isbnBusqueda,
                    "Libro no encontrado", JOptionPane.WARNING_MESSAGE);
    
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        catalogo.sort(Comparator.comparing(Libro::getIsbn));
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void comboModificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModificarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModificarCategoriaActionPerformed

    private void btnModificarLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLimpiarActionPerformed
        
        txtModificarTitulo.setText("");
        txtModificarPrecio.setText("");
        txtModificarPaginas.setText("");
        comboModificarCategoria.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnModificarLimpiarActionPerformed

    private void btnModificarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVolverActionPerformed
        jdialog3Modificar.setVisible(false);
    }//GEN-LAST:event_btnModificarVolverActionPerformed

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
        //primero, recogemos los nuevos valores desde los campos de texto y ComboBox
    String nuevoTitulo = txtModificarTitulo.getText();
    Categoria nuevaCategoria = (Categoria) comboModificarCategoria.getSelectedItem();
    int nuevoPrecio = Integer.parseInt(txtModificarPrecio.getText());
    int nuevoPaginas = Integer.parseInt(txtModificarPaginas.getText());

    //ahor abuscamos el libro en el catálogo usando el isbn que le habíamos pedido
    for (Libro l : catalogo) {
        if (l.getIsbn() == isbnLibroModificar) {
            // Actualizar los valores del libro con los nuevos valores
            l.titulo = nuevoTitulo;
            l.precio = nuevoPrecio;
            l.nPaginas = nuevoPaginas;
            l.setCategoria(nuevaCategoria);
            
            //mostramos un mensajito de éxito
            JOptionPane.showMessageDialog(null, "Libro modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            //cerramos el JDialog de modificar después de modificar el libro
            jdialog3Modificar.setVisible(false);
            return;
        }
    }

    //si no se encuentra el libro con el ISBN almacenado, mostramos un mensaje de error
    JOptionPane.showMessageDialog(null, "No se encontró ningún libro con el ISBN proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         String isbnModificar = JOptionPane.showInputDialog(null, "Introduzca el ISBN del libro", "Modificar libro", JOptionPane.QUESTION_MESSAGE);
    
    //nos aseguramos de que se haya introducido un isbn
    if (isbnModificar != null && !isbnModificar.isEmpty()) {
        isbnLibroModificar = Integer.parseInt(isbnModificar); // Almacenar el isbn del libro a modificar
        
        //ahora buscamos el libro usando el isbn proporcionado
        for (Libro l : catalogo) {
            if (l.getIsbn() == isbnLibroModificar) {
                /*ahora muestro los datos del libro en el labelResumen. He necesitado HTML para que haga saltos de línea, no sé
                cómo configurar las labels para que hagan eso de otra forma... */
                labelResumen.setText("<html>" + "ISBN: " + l.getIsbn() + "<br>" +
                       "Título: " + l.titulo + "<br>" +
                       "Categoria: " + l.getCategoria() + "<br>" + 
                       "Precio: " + l.precio + "<br>" +
                       "Nº de página: " + l.nPaginas + "</html>");
                            
                
                //mostramos el JDialog para modificar el libro
                jdialog3Modificar.setVisible(true);
                return; 
            }
        }
        
        //si el libro no se encuentra en el catálogo, mostramos un mensaje de error
        JOptionPane.showMessageDialog(null, "El libro con el ISBN " + isbnLibroModificar + " no se encuentra en el catálogo.", "Libro no encontrado", JOptionPane.ERROR_MESSAGE);
    }  
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Lectores luis = new Lectores(catalogo, lector1);
        luis.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Lectores luisa = new Lectores(catalogo, lector2);
        luisa.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jdialog4SalaLectura.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnAñadir2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarAñadir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnModificarLimpiar;
    private javax.swing.JButton btnModificarVolver;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVolverAñadir;
    private javax.swing.JButton btnVolverCatalogo;
    private javax.swing.JComboBox<Categoria> comboCategoria;
    private javax.swing.JComboBox<Categoria> comboModificarCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDialog jdialog1Añadir;
    private javax.swing.JDialog jdialog2Ver;
    private javax.swing.JDialog jdialog3Modificar;
    private javax.swing.JDialog jdialog4SalaLectura;
    private javax.swing.JLabel labelContador;
    private javax.swing.JLabel labelERROR;
    private javax.swing.JLabel labelResumen;
    private javax.swing.JList<String> lector1;
    private javax.swing.JList<String> lector2;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtModificarPaginas;
    private javax.swing.JTextField txtModificarPrecio;
    private javax.swing.JTextField txtModificarTitulo;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

private void loadComboBox() { //necesitamos este método para que el combobox pille los valores del Enum
        comboCategoria.setModel(new DefaultComboBoxModel<>(Categoria.values()));
        comboCategoria.setSelectedIndex(-1); //esto hace que el combobox por defecto aparezca vacío, por limpieza
        
        comboModificarCategoria.setModel(new DefaultComboBoxModel<>(Categoria.values()));
        comboModificarCategoria.setSelectedIndex(-1);
        
    }

public static int getContadorLibros() {
    return Libro.contadorLibros;
    }

private boolean isbnYaExiste(int isbn) { //este método comprueba si ya existe el isbn cuando creamos un objeto, para evitar que se repitan 
    for (Libro l : catalogo) {
        if (l.getIsbn() == isbn) {
            return true;
            }
        }
    return false;
    }









}


